import Session from "../data/Session"

export const MOCK_SESSIONS: Session[] = [
  new Session(
    "Mike Burke",
    "District",
    "Direct Service",
    "Mental Health Counseling",
    "Student 1",
    "School",
    "Notes",
    "Present",
    "01/02/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "20",
    "20"
  ),
  new Session(
    "Mike Burke",
    "District",
    "Direct Service",
    "Mental Health Counseling",
    "Student 1",
    "School",
    "Notes",
    "Present",
    "01/04/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "30",
    "30"
  ),
  new Session(
    "Mike Burke",
    "District",
    "Direct Service",
    "Mental Health Counseling",
    "Student 1",
    "School",
    "Notes",
    "Present",
    "01/06/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "30",
    "30"
  ),
  new Session(
    "Mike Burke",
    "District",
    "Direct Service",
    "Mental Health Counseling",
    "Student 1",
    "School",
    "Notes",
    "Absent - No Notice",
    "01/16/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "30",
    "30"
  ),
  new Session(
    "Mike Burke",
    "District",
    "InDirect Service",
    "Consultation",
    "Student 1",
    "School",
    "Notes",
    "",
    "01/010/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "30",
    "30"
  ),
  new Session(
    "Jacek McGuinness",
    "District",
    "Direct Service",
    "Mental Health Counseling",
    "Student 1",
    "School",
    "Notes",
    "Present",
    "01/12/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "30",
    "30"
  ),
  new Session(
    "Jacek McGuinness",
    "District",
    "InDirect Service",
    "Consultation",
    "Student 1",
    "School",
    "Notes",
    "",
    "01/02/2024",
    "11:00 A.M.",
    "11:30 A.M.",
    "0",
    "45",
    "45"
  ),
]
